# Please read comments in environment.yml
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - build
  - bump-my-version
  - flake8
  - flake8-pyproject
  - icecream
  - ipympl
  - jupyterlab
  - mypy
  - pylint
  - pytest
  - pytest-cov
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-apidoc
  - sphinxcontrib-autoprogram
  - twine
  - pip
  - pip:
      - ufmt
