"""
Coordinate types: geographic and projected, point and box.

This module also supports coordinate transformations.

Examples

>>> lps_lgrs_box = LpsLgrsBox(
...     longitudinal_band="A", easting_area="Z", northing_area="S",
...     easting="13590", northing="08480"
... )
>>> alt_lps_lgrs_box = LpsLgrsBox.from_string("AZS1359008480")
>>> alt_lps_lgrs_box.is_equal_to(lps_lgrs_box, error=True)
True
"""

# Copyright © 2026, Ethan I. Schaefer (eschaefer@seti.org)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.

###############################################################################
# region> IMPORT
###############################################################################
# Special.
from __future__ import annotations

# Standard.
import abc as _abc
import collections as _collections
import dataclasses as _dataclasses
import functools as _functools
import math as _math
import types as _types
import typing as _typing

# External.
import pyproj as _pyproj
import regex as _regex

# Internal.
import lgrs.caching as _caching
import lgrs.database as _database
import lgrs.exceptions as _exceptions
import lgrs.srs.srs as _srs
import lgrs.srs.wkt as _wkt

# endregion
###############################################################################
# region> TYPE ALIASES
###############################################################################
type _ToMethod = _collections.abc.Callable[..., BaseCoordinate]


# endregion
###############################################################################
# region> UTILITIES: REDIRECTION & CACHING
###############################################################################
def _cache_new_cousin(func: _ToMethod) -> _ToMethod:
    """
    Cache the new `BaseCoordinate` returned whenever `func()` is called.`.

    See `_redirect()` for a description of what a "cousin" is.

    Parameters
    ----------
    func : callable
        The hidden `._to_*()` method to be decorated.

    Returns
    -------
    wrapped : callable
        The wrapped `func`.
    """

    # Wrap function.
    @_functools.wraps(func)
    def wrapped(self: BaseCoordinate, **kwargs) -> BaseCoordinate:
        new = func(self, **kwargs)
        self._register_cousin(new)
        return new

    # Return wrapped function.
    return wrapped


def _calc_na_letterset(zone_number: int) -> int:
    # TODO: Determine if the "- 1" (which appears in the reference
    #  code but not in Eq. 83) is correct.
    na_letterset = (zone_number - 1) % 3  # Eq. 83
    return na_letterset


def _redirect(func: _ToMethod) -> _ToMethod:
    """
    For `.to_*()`, get from cache or redirect to `._to_*()`.

    A method decorated with this function will never be called (and
    therefore can be empty). Rather, a suitable "cousin" `BaseCoordinate`
    instance is returned from the cache, if possible. Otherwise, the call
    is redirected to `self._to_*()` for creation and the new instance is
    returned.

    A "cousin" is another `BaseCoordinate` whose location (after
    transformation) and constraints are the same as those of `self`. Cousins
    are often generated during intermediate calculations, whether internal
    or external (i.e., by the user), so caching them into cousin groups
    improves efficiency. Note that a cousin group is only guaranteed to
    include those cousins generated by a transformation chain from a
    common root. Therefore, cousins that are wholly independently
    instantiated may not be grouped together.

    Parameters
    ----------
    func : callable
        The public `.to_*()` method to be decorated. It will never be
        called.

    Returns
    -------
    wrapped : callable
        The wrapped `func`.
    """

    @_functools.wraps(func)
    def wrapped(self: BaseCoordinate) -> BaseCoordinate:
        # Note: `func` itself is only used for its return type and name.
        cached = self._get_cached_cousin(func)
        if cached is not None:
            return cached
        new = getattr(self, f"_{func.__name__}")()
        return new

    return wrapped


@_functools.cache
def _resolve_out_types(func: _collections.abc.Callable) -> tuple[type, ...]:
    out_hint = _typing.get_type_hints(func)["return"]
    if isinstance(out_hint, _types.UnionType):
        out_types = _typing.get_args(out_hint)
    else:
        out_types = (out_hint,)
    return out_types


def _return_none(self: BaseCoordinate) -> None:
    return None


# endregion
###############################################################################
# region> UTILITIES: REGEX
###############################################################################
def _compile_regex_without_i_and_o(pattern: str) -> _regex.Pattern:
    clean_pattern = _regex.sub("[A-Z]-[A-Z]", _remove_i_and_o, pattern)
    return _regex.compile(clean_pattern)


def _expand_char_range(char_range: str) -> list[str]:
    start_char, end_char = char_range.split("-")
    chars = [chr(i) for i in range(ord(start_char), ord(end_char) + 1)]
    return chars


def _extract_chars_from_pattern(
    pattern: _regex.Pattern | None = None,
    name: str | None = None,
    *,
    pre: str = "",
    post: str = "",
) -> str:
    # Note: M2025 assigns a value to each character in each table.
    # However, in all M2025 equations, characters are treated as 0-
    # indexed. Therefore, a string (rather than mapping) is sufficient.
    # Note: Extraction is not general (e.g., does not accommodate
    # escaped ")").
    chars = _regex.search(
        rf"\(\?P<{name}>\[(?P<gpattern>.*?)]\)", pattern.pattern
    ).group("gpattern")
    final = pre + chars + post
    return final


def _format_as_five_digit_int(n: float) -> str:
    return f"{_smart_truncate(n):05}"


def _make_en_pattern(*digit_count: int) -> str:
    pattern = "|".join(
        f"((?P<easting>[0-9]{{{i}}})(?P<northing>[0-9]{{{i}}}))"
        for i in sorted(digit_count, reverse=True)
    )
    return pattern


def _remove_i_and_o(match: _regex.Match) -> str:
    expanded = _expand_char_range(match.group())
    for char in ("I", "O"):
        try:
            expanded.remove(char)
        except ValueError:
            continue
    return "".join(expanded)


# endregion
###############################################################################
# region> UTILITIES: OTHER
###############################################################################
def _as_str(str_or_none: str | None) -> str:
    if str_or_none is None:
        return ""
    else:
        return str_or_none


def _easy_dataclass(cls: type[BaseCoordinate]) -> type[BaseCoordinate]:
    """
    Force constraints to end of call signature, string representation.

    Decorating a `BaseCoordinate` subclass with this function makes it a
    frozen dataclass and ensures that field order has `_BaseCoordinate`
    fields--assumed to be constraints--pushed to the end of both
    `cls.__init__()` call signatures and the output of `cls.__repr__()`.
    Since constraints are assumed to be less important to most users,
    pushing them to the end is preferable.

    Parameters
    ----------
    cls : type
        The `BaseCoordinate` subclass to decorate.

    Returns
    -------
    decorated : type
        The decorated `cls`.
    """
    # Isolate non-universal fields.
    naive_dataclass = _dataclasses.dataclass(cls, frozen=True)
    univ_field_name_set = {
        field.name for field in _dataclasses.fields(_BaseCoordinate)
    }
    non_univ_fields = [
        field
        for field in _dataclasses.fields(naive_dataclass)
        if field.name not in univ_field_name_set
    ]

    # Insert "shadow" dataclass in inheritance, to push universal fields
    # to end.
    field_annotations = {field.name: field.type for field in non_univ_fields}
    shadow_cls = type(
        f"_Shadow{cls.__name__}",
        (_AbstractBaseCoordinate,),
        {"__annotations__": field_annotations},
    )
    shadow_dataclass = _dataclasses.dataclass(shadow_cls, frozen=True)
    mro = (
        *cls.__mro__[: cls.__mro__.index(_AbstractBaseCoordinate)],
        *shadow_dataclass.__mro__,
    )
    twin_cls = type(cls.__name__, mro, {})
    # Note: Copies docstring, etc. from `cls` to `twin_cls`.
    _functools.update_wrapper(twin_cls, cls, updated=())
    del twin_cls.__wrapped__  # Avoid confusion, duplicate doctests.

    # Create and return outer dataclass.
    dataclass = _dataclasses.dataclass(frozen=True)(twin_cls)
    return dataclass


def _smart_truncate(f: float, *, tolerance: float = 0.001) -> int:
    # TODO: Determine whether `tolerance` is a good choice. Code
    #  mimics `check_decimal_round()` of reference code and presumably
    #  mitigates undesirable results that arise due to floating-point
    #  precision.
    nearest_int = round(f)
    if abs(nearest_int - f) < tolerance:
        return nearest_int
    else:
        return _floor(f)


_floor = _math.floor


# endregion
###############################################################################
# region> COORDINATE BASE TYPES
###############################################################################
class _AbstractBaseCoordinate(_abc.ABC):
    pass


# Note: `_BaseCoordinate` is useful for defining behavior that depends
# on the class being a dataclass. Conversely, `BaseCoordinate` and its
# hidden subclasses are useful for defining all other behavior (without
# accidentally implying dataclass fields).
@_dataclasses.dataclass(frozen=True, kw_only=True)
class _BaseCoordinate(_AbstractBaseCoordinate):

    # * FIELDS AND VALIDATION. ────────────────────────────────────────
    _fields_cached: _typing.ClassVar[tuple[_dataclasses.Field, ...]]
    prefer_lps: bool = False
    extended_ltm: bool = False
    global_ltm: bool = False
    validate: _dataclasses.InitVar[bool] = True

    def _register_validation(self) -> None:
        object.__setattr__(self, "_was_validated", True)

    def _validate(self) -> None:
        for field in self._get_fields():
            result = getattr(self, f"_validate_{field.name}")()
            if result is not None:
                # Note: Cannot assign directly, because `self` is a
                # frozen dataclass.
                object.__setattr__(self, field.name, result)
        # Note: `._init_kwargs` effectively freezes values, which may
        # not be finalized until validation completes. It should not be
        # assigned until after validation.
        assert "_init_kwargs" not in self.__dict__
        self._register_validation()

    def _validate_global_ltm(self) -> None:
        if self.global_ltm:
            if self.prefer_lps or self.extended_ltm:
                raise _exceptions.MalformedCoordinate(
                    "If `global_ltm` is `True`, `prefer_lps` and "
                    "`extended_ltm` must be `False` (or `None`)."
                )

    _validate_prefer_lps = _return_none
    _validate_extended_ltm = _return_none

    # * INITIALIZATION. ───────────────────────────────────────────────
    def __post_init__(self, validate: bool) -> None:
        if validate:
            self._validate()

    @_functools.cached_property
    def _init_kwargs(self) -> dict[str, _typing.Any]:
        return {
            field.name: getattr(self, field.name)
            for field in self._get_fields()
        }

    # TODO: Un-skip doctest once complete validation is implemented.
    def with_constraints(
        self,
        *,
        prefer_lps: bool | None = None,
        extended_ltm: bool | None = None,
        global_ltm: bool | None = None,
        validate: bool | None = None,
        copy: bool = False,
    ) -> _typing.Self:
        """
        Get a version of `self` with the specified constraints.

        For any constraint that is not specified (or specified as `None`), the
        corresponding value from `self` is used.

        Parameters
        ----------
        prefer_lps : bool, optional
            See `LatLonPoint` documentation.
        extended_ltm : bool, optional
            See `LatLonPoint` documentation.
        global_ltm : bool, optional
            See `LatLonPoint` documentation.
        validate : bool, optional
            See `LatLonPoint` documentation.
        copy : bool, optional
            Whether to ensure that the returned instance is not `self`. If not
            specified (`None`), set to `True` unless `self` is suitable.

        Returns
        -------
        version : BaseCoordinate
            Version of `self` with the specified constraints.

        Examples
        --------
        >>> geo_point = LatLonPoint(81, 0, extended_ltm=True)
        >>> ltm_point = geo_point.to_lps_or_ltm()
        >>> isinstance(ltm_point, LtmPoint)
        True
        >>> illegal_point = ltm_point.with_constraints(extended_ltm=False)  # doctest: +SKIP
        Traceback (most recent call last):
          ...
        lgrs.exceptions.MalformedCoordinate:
          ...
        """  # noqa: E501

        # Resolve new initialization kwargs.
        new_init_kwargs = self._init_kwargs.copy()
        if prefer_lps is not None:
            new_init_kwargs["prefer_lps"] = prefer_lps
        if global_ltm is not None:
            new_init_kwargs["global_ltm"] = global_ltm
        if extended_ltm is not None:
            new_init_kwargs["extended_ltm"] = extended_ltm

        # Return `self`, if suitable and allowed.
        if (
            not copy
            and not validate  # May be `None`.
            and new_init_kwargs == self._init_kwargs
        ):
            return self

        # Create and return copy, constrained as specified.
        if validate is None:
            validate = True  # *REASSIGNMENT*
        new = type(self)(**new_init_kwargs, validate=validate)
        return new

    # * FIELD SUPPORT. ────────────────────────────────────────────────
    def __iter__(self) -> _collections.abc.Iterable:
        return iter(self._init_kwargs.values())

    @_functools.cached_property
    def _constraint_keys(self) -> tuple[str, ...]:
        # Note: Assumes that all fields of `_BaseCoordinate` are
        # constraints, consistent with `_easy_dataclass()`.
        constraint_keys = tuple(
            field.name for field in _BaseCoordinate._get_fields()
        )
        _BaseCoordinate._constraint_keys = constraint_keys
        return constraint_keys

    @classmethod
    @_functools.cache
    def _get_fields(cls) -> tuple[_dataclasses.Field, ...]:
        return _dataclasses.fields(cls)

    @classmethod
    @_functools.cache
    def _get_field_name_to_type(cls) -> dict[str, type]:
        name_to_type = {}
        field_name_set = {field.name for field in cls._get_fields()}
        for name, typ in _typing.get_type_hints(cls).items():
            if name not in field_name_set:
                continue
            if isinstance(typ, _types.UnionType):
                types = list(_typing.get_args(typ))
                types.remove(type(None))
                (typ,) = types  # *REASSIGNMENT*
            name_to_type[name] = typ
        return name_to_type

    @_functools.cached_property
    def _nonconstraint_kwargs(self) -> dict[str, _typing.Any]:
        return {
            field_name: field_val
            for field_name, field_val in self._init_kwargs.items()
            if field_name not in self._constraint_keys
        }


class BaseCoordinate(_BaseCoordinate):
    """The base class for all coordinates, both points and grid boxes."""

    _template: _collections.abc.Callable | str | None = None
    _was_validated: bool = False

    # * BASIC BEHAVIOR. ───────────────────────────────────────────────
    def __copy__(self) -> _typing.Self:
        return self.copy()

    def __str__(self) -> str:
        return self.string

    # * INSTANTIATION. ────────────────────────────────────────────────
    @classmethod
    def _from_ref_string(cls, string: str) -> _typing.Self:
        # Note: Unlike `BoxCoordinate.from_string()`, this method exists
        # solely to support parsing values from
        # `LGRS_Coordinate_Conversion`.
        parts = tuple(string.split(" "))
        if len(parts) == 1:
            raise _exceptions.MalformedCoordinate(
                "`string` must be space-delimited"
            )
        field_name_to_type = cls._get_field_name_to_type()
        if len(parts) > len(field_name_to_type):
            raise _exceptions.MalformedCoordinate(
                "`string` contains too many space-delimited "
                f"components: {string!r}"
            )
        init_kwargs = {
            name: typ(part)
            for part, (name, typ) in zip(parts, field_name_to_type.items())
        }
        return cls(**init_kwargs)

    # * VALIDATION. ───────────────────────────────────────────────────
    def _raise_malformed_coordinate(
        self,
        middle: str,
        *,
        attr_name: str,
        if_attr_name: str | None = None,
    ) -> _typing.NoReturn:
        if if_attr_name is None:
            prefix = ""
        else:
            prefix = f"For `{if_attr_name}={getattr(self, if_attr_name)!r}`, "
        raise _exceptions.MalformedCoordinate(
            f"{prefix}"
            f"`{attr_name}` must be "
            f"{middle}"
            f", not: {getattr(self, attr_name)!r}"
        )

    @staticmethod
    def _raise_unexpected(
        func: _collections.abc.Callable | None = None,
    ) -> _typing.NoReturn:
        if func is not None:
            func()
        raise TypeError("An unexpected error occurred.")

    def _validate_against_closed_interval(
        self,
        *,
        attr_name: str,
        minimum: _typing.Any,
        maximum: _typing.Any,
        if_attr_name: str | None = None,
        coerce_str: bool = False,
    ) -> None:
        val = getattr(self, attr_name)
        if coerce_str:
            val = float(val)  # *REASSIGNMENT*
        if not (minimum <= val <= maximum):
            self._raise_malformed_coordinate(
                f"between {minimum} and {maximum}, inclusive",
                attr_name=attr_name,
                if_attr_name=if_attr_name,
            )

    def _validate_against_sequence(
        self,
        *,
        attr_name: str,
        sequence: _collections.abc.Sequence,
        if_attr_name: str | None = None,
    ) -> None:
        val = getattr(self, attr_name)
        if val not in sequence:
            if len(sequence) == 2:
                item_1, item_2 = sequence
                middle = f"{item_1!r} or {item_2!r}"
            else:
                middle = (
                    f"one of {', '.join(map(repr, sequence[:-1]))}, "
                    f"or {sequence[-1]!r}"
                )
            self._raise_malformed_coordinate(
                middle=middle, attr_name=attr_name, if_attr_name=if_attr_name
            )

    def _validate_hemisphere(self) -> None:
        self._validate_against_sequence(
            attr_name="hemisphere", sequence=("N", "S")
        )

    def validate(self, *, revalidate: bool = False) -> None:
        """
        Validate this coordinate.

        Use this method to validate the instance or confirm that it has already
        been validated. Note that validating at initialization instead is
        generally recommended, as doing so is faster and avoids creating
        invalid instances.

        Parameters
        ----------
        revalidate : bool, default=False
            Whether to re-validate the instance if it has already been
            validated. This option is likely only useful in special cases.

        Returns
        -------
        None

        Raises
        ------
        lgrs.Exceptions.MalformedCoordinate
            If the instance is invalid. Unlike at-initialization validation,
            an instance is considered invalid even if its values are merely
            not conformed. See Examples.

        Examples
        --------
        >>> latlon_1 = LatLonPoint(45, 182)
        >>> latlon_1.longitude == -178  # Conformed.
        True
        >>> latlon_2 = LatLonPoint(45, 182, validate=False)
        >>> latlon_2.longitude == -178   # Not conformed.
        False
        >>> latlon_2.validate()  # doctest: +NORMALIZE_WHITESPACE
        Traceback (most recent call last):
          ...
        lgrs.exceptions.MalformedCoordinate:
          Validation conformed the following value(s):
            longitude: 182 --> -178

        """
        if not revalidate and self._was_validated:
            return
        new = self.copy(validate=False)
        try:
            new._validate()
        except _exceptions.MalformedCoordinate:
            self._unregister_cousins(*self._cousins)
            raise
        if new._init_kwargs == self._init_kwargs:
            self._register_validation()
            return
        # TODO: Think carefully about whether to unregister cousins.
        #  There is currently no guard against these cousins being re-
        #  created by `.to_*()`, so unregistering them has no benefit.
        #  Options are:
        #    (1) Leave cousins intact.
        #    (2) Introduce (perhaps optionally) a way to label an
        #        instance as invalid, to prohibit use, and apply that
        #        to all cousins.
        #    (3) Same as #2 but also conform self, if possible.
        #  Since `.validate()` is only for special use cases, probably
        #  #1.
        self._unregister_cousins(*self._cousins)
        change_lines = []
        for k, new_v in new._init_kwargs.items():
            old_v = self._init_kwargs[k]
            if new_v != old_v:
                change_lines.append(f"    {k}: {old_v!r} --> {new_v!r}")
        raise _exceptions.MalformedCoordinate(
            "\n"
            "  Validation conformed the following value(s):\n"
            f"{'\n'.join(change_lines)}"
        )

    # * PUBLIC DATA. ──────────────────────────────────────────────────
    @_functools.cached_property
    def string(self) -> str:
        """
        The string representation of the coordinate.

        Equivalent to `str(self)`. Cached after first use.
        """
        match self._template:
            case None:
                string = "".join(self._iter_value_strings())
            case str():
                string = self._template.format(**self._init_kwargs)
            case _:
                string = self._template()
        return string

    # * GENERAL PUBLIC METHODS. ───────────────────────────────────────
    @staticmethod
    def _conform_to_latlon_points(
        *coords: BaseCoordinate, center: bool
    ) -> _typing.Iterator[LatLonPoint]:
        for coord in coords:
            if center and isinstance(coord, BoxCoordinate):
                yield coord.center_latlon
            else:
                yield coord.to_latlon()

    @property
    def _geod(self) -> _pyproj.Geod:
        geod = _pyproj.Geod(sphere=True, a=_wkt.LUNAR_RADIUS)
        type(self)._geod = geod  # Reuse this instance.
        return geod

    @classmethod
    def _is_x_based(cls, prefix: str) -> bool:
        if issubclass(cls, LatLonPoint):
            raise TypeError("`LatLonPoint` is neither LPS- nor LTM-based")
        return cls.__name__.startswith(prefix)

    # TODO: Un-skip doctest once complete validation is implemented.
    def copy(self, *, validate: bool = False) -> _typing.Self:
        """
        Create independent copy of this coordinate.

        Although `copy` is a different instance from `self`, its cache is not
        guaranteed independnet. See Examples.

        Parameters
        ----------
        validate : bool, default=False
            Whether to validate the copy. The default is `False` because it's
            assumed that either `self` was validated or intentionally not
            validated, because its values are known to be valid.

        Returns
        -------
        copy : typing.Self
            A copy of this coordinate.

        Examples
        --------
        >>> import lgrs.caching
        >>> lgrs.caching.enable_caching()
        >>> example_latlon = LatLonPoint(0, 0)
        >>> example_lgrs = example_latlon.to_lgrs()
        >>> alt_latlon = example_latlon.copy()
        >>> example_latlon is alt_latlon
        False
        >>> example_latlon.to_lgrs() is example_latlon.to_lgrs()
        True
        >>> example_latlon.to_lgrs() is alt_latlon.to_lgrs()  # doctest: +SKIP

        Whether this final statement evaluates as `True` or `False` is not
        guaranteed. To guarantee independence, caching should be disabled
        globally by `lgrs.caching.enable_caching(False)`.
        """
        # Note: `self` can only exist if validated or explicitly not
        # validated. Either way, defaulting `validate` to `False` is
        # appropriate.
        new = type(self)(
            **self._init_kwargs,
            validate=(validate and not self._was_validated),
        )
        return new

    def distance_to(
        self, other: BaseCoordinate, *, center: bool = False
    ) -> float:
        """
        Calculate the geodesic distance between two coordinates, in meters.

        For any box coordinate (`self` and/or `other`), distance is measured
        to a representative point, as determined by `center`.

        Parameters
        ----------
        other : BaseCoordinate
            The other coordinate.
        center : bool, default=False
            Whether to use the center of any box coordinate instead of the
            lower-left (grid-southwest) corner.

        Returns
        -------
        distance : float
            The geodesic distance between `self` and `other`, in meters.

        See Also
        --------
        contains : Whether a box coordinate contains another coordinate.
        grid_distance_to : Point-to-point grid distance.

        Examples
        --------
        >>> latlon_point = LatLonPoint(0, 0)
        >>> acc_box = LtmAccBox.from_string("23NFF-001-001")
        >>> latlon_point.distance_to(acc_box)
        1.415638994018731
        >>> latlon_point.distance_to(acc_box, center=True)
        2.1234979460292074
        """
        self_latlon_point, other_latlon_point = self._conform_to_latlon_points(
            self, other, center=center
        )
        _, _, dist = self._geod.inv(
            self_latlon_point.longitude,
            self_latlon_point.latitude,
            other_latlon_point.longitude,
            other_latlon_point.latitude,
        )
        return dist

    def grid_distance_to(
        self,
        other: BaseCoordinate,
        *,
        center: bool = False,
        system: str | None = None,
    ) -> float:
        """
        Calculate the grid distance between two coordinates, in meters.

        For any box coordinate (`self` and/or `other`), distance is measured
        to a representative point, as determined by `center`.

        Parameters
        ----------
        other : BaseCoordinate
            The other coordinate.
        center : bool, default=False
            Whether to use the center of any box coordinate instead of the
            lower-left (grid-southwest) corner.
        system : str, optional
            The system (LPS or LTM) in which to calculate the grid distance. By
            default, if `self` and `other` use the same system, distance is
            calculated in that system. Alternatively, the system may be
            specified by "LPS" or "LTM" (case is ignored).

        Returns
        -------
        distance : float
            The grid distance between `self` and `other`, in meters.

        Raises
        ------
        TypeError
            If `system` is not recognized, or if `system` is not specified
            (`None`) and `self` and `other` use different systems.
        lgrs.Exceptions.MalformedCoordinate
            If `system="LPS"` but `self` and/or `other` are outside the LPS
            region supported by LGRS.

        See Also
        --------
        contains : Whether a box coordinate contains another coordinate.
        distance_to : Point-to-point geodesic distance.

        Examples
        --------
        >>> latlon_point = LatLonPoint(0, 0)
        >>> acc_box = LtmAccBox.from_string("23NFF-001-001")
        >>> latlon_point.grid_distance_to(acc_box)
        1.4142135623730951
        >>> latlon_point.distance_to(acc_box, center=True)
        2.1234979460292074
        """
        match system:
            case "LPS":
                convert = BaseCoordinate.to_lps
            case "LTM":
                convert = BaseCoordinate.to_ltm
            case None:
                convert = BaseCoordinate.to_lps_or_ltm
            case _:
                raise TypeError(f"`system` not recognized: {system!r}")
        self_box, other_box = map(
            convert, self._conform_to_latlon_points(self, other, center=center)
        )
        if (
            system is None
            and self_box.is_lps_based() != other_box.is_lps_based()
        ):
            raise TypeError(
                "`self` and `other` are not in the same system (LPS or LTM)"
            )
        dist = _math.dist(
            (self_box.easting, self_box.northing),
            (other_box.easting, other_box.northing),
        )
        return dist

    # TODO: Decide whether to support mixed types.
    def is_equal_to(
        self,
        other: _typing.Self,
        *,
        error: bool = False,
        constraints: bool = False,
    ) -> bool:
        """
        Test whether two coordinates are equal, optionally including
        constraints.

        Note that::

            coord_1 == coord_2

        is equivalent to::

            coord_1.is_equal_to(coord_2, constraints=True)

        except that the latter does not support mixed types.

        Parameters
        ----------
        other : BaseCoordinate
            The other coordinate to compare to.
        error : bool, default=False
            Whether to raise a descriptive error rather than return `False`.
        constraints : bool, default=False
            Whether to include constraints when evaluating equality. If
            `False`, only coordinate values are compared. If `True`, each
            constraint is also compared.

        Returns
        -------
        is_equal : bool
            Whether `self` and `other` are equal.

        Raises
        ------
        TypeError
            If `self` and `other` are of different types.

        Examples
        --------
        >>> latlon_point_1 = LatLonPoint(0, 0)
        >>> latlon_point_2 = LatLonPoint(0, 0, extended_ltm=True)
        >>> latlon_point_1.is_equal_to(latlon_point_2)
        True
        >>> latlon_point_1.is_equal_to(latlon_point_2, constraints=True)
        False
        """
        # Compare.
        if constraints:
            excluded_field_names = ()
        else:
            excluded_field_names = self._constraint_keys
        err_lines = []
        for field_name, self_val in self._init_kwargs.items():
            if field_name in excluded_field_names:
                continue
            other_val = getattr(other, field_name)
            if self_val != other_val:
                if not error:
                    return False
                err_lines.append(f"  {field_name!r} values differ:")
                err_lines.append(f"    {self_val!r} vs. {other_val!r}")
        if err_lines:
            raise TypeError("\n" + "\n".join(err_lines))
        return True

    # TODO: Consider an `.is_close_to()` that automatically accounts for
    #  both `.precision` (where applicable) and the inferred conversion
    #  sequence. For example, comparing a `LatLonPoint` and a
    #  `LpsAccBox` would allow for expected imprecision in the
    #  `LatLonPoint` --> `LpsPoint` --> `LpsLgrs` sequence, and
    #  comparing a `LatLonPoint` to a `LatLonPoint` would allow for the
    #  expected round-trip disparity.

    @classmethod
    @_functools.cache
    def is_lps_based(cls):
        """
        Whether the coordinate is based in the LPS system.

        Returns
        -------
        is_lps_based : bool
            Whether the coordinate is based in the LPS system.

        Raises
        ------
        TypeError
            If instance is a `LatLonPoint`.

        See Also
        --------
        is_ltm_based : Counterpart for the LTM system.

        Examples
        --------
        >>> lps_lgrs_box = LpsLgrsBox.from_string("AZS1359008480")
        >>> lps_lgrs_box.is_lps_based()
        True
        >>> LpsLgrsBox.is_lps_based()  # Can call on a class, too.
        True
        >>> ltm_acc_box = LtmAccBox.from_string("29TCVK738P376")
        >>> ltm_acc_box.is_lps_based()
        False
        """
        return cls._is_x_based("Lps")

    @classmethod
    @_functools.cache
    def is_ltm_based(cls):
        """
        Whether the coordinate is based in the LTM system.

        Returns
        -------
        is_ltm_based : bool
            Whether the coordinate is based in the LTM system.

        Raises
        ------
        TypeError
            If instance is a `LatLonPoint`.

        See Also
        --------
        is_lps_based : Counterpart for the LPS system.

        Examples
        --------
        >>> ltm_acc_box = LtmAccBox.from_string("29TCVK738P376")
        >>> ltm_acc_box.is_ltm_based()
        True
        >>> LtmAccBox.is_ltm_based()  # Can call on a class, too.
        True
        >>> lps_lgrs_box = LpsLgrsBox.from_string("AZS1359008480")
        >>> lps_lgrs_box.is_ltm_based()
        False
        """
        return cls._is_x_based("Ltm")

    def replace(
        self, *, validate: bool = True, copy: bool = True, **overrides
    ) -> _typing.Self:
        """
        Create new instance with modified values and/or constraints.

        The new instance will have the same values and constraints as `self`,
        except where explicitly overridden by `overrides`.

        Parameters
        ----------
        validate : bool, default=True
            Whether to validate the new instance.
        copy : bool, default=True
            Whether to ensure that the new instance is not `self`. If `False`
            and any `overrides` have the same values as `self`, `self` is
            returned.
        **overrides
            Keyword arguments specifying initialization parameters (values and
            constraints) for the new instance.

        Returns
        -------
        new : typing.Self
            The new instance.

        Raises
        ------
        lgrs.Exceptions.MalformedCoordinate
            If `new` would be invalid and `validate` is `True`.

        Examples
        --------
        >>> lat_lon_point_1 = LatLonPoint(0, 0)
        >>> lat_lon_point_2 = lat_lon_point_1.replace(longitude=1)
        >>> lat_lon_point_2 == LatLonPoint(0, 1)
        True
        """
        if not copy and not overrides:
            return self
        init_kwargs = self._init_kwargs.copy()
        init_kwargs.update(overrides)
        return type(self)(**init_kwargs, validate=validate)

    # * TRANSFORMATION CACHING. ───────────────────────────────────────
    # Note: See `_redirect()` for a description of what a "cousin" is.

    @property
    def _cousins(self) -> _collections.deque[BaseCoordinate]:
        cached_cousins = _caching._query_weak_cache(
            self._root, key="cousins", default=None
        )
        if cached_cousins is None:
            new_cousins = _collections.deque()
            new_cousins.appendleft(self)
            _caching._store_to_weak_cache(
                self._root, key="cousins", value=new_cousins
            )
            return new_cousins
        else:
            return cached_cousins

    def _get_cached_cousin(self, func: _ToMethod) -> BaseCoordinate | None:
        out_types = _resolve_out_types(func)
        for cousin in self._cousins:
            if isinstance(cousin, out_types):
                return cousin
        return None

    def _register_cousin(self, cousin: BaseCoordinate) -> None:
        if _caching._CACHING_IS_ENABLED:
            # Note: Only assign `._root` if transformation is reversible
            # (lossless).
            if not isinstance(cousin, BoxCoordinate) or isinstance(
                self, BoxCoordinate
            ):
                object.__setattr__(cousin, "_root", self._root)
            self._cousins.appendleft(cousin)

    @_functools.cached_property
    def _root(self) -> BaseCoordinate:
        # Note: Overridden when instantiated by transformation.
        return self

    def _unregister_cousins(self, *cousins: BaseCoordinate) -> None:
        if _caching._CACHING_IS_ENABLED:
            for cousin in cousins:
                self._cousins.remove(cousin)

    @_functools.cached_property
    def constraints(self) -> _types.MappingProxyType[str, bool]:
        """The constraints on the instance, as a read-only mapping."""
        return _types.MappingProxyType(
            {key: self._init_kwargs[key] for key in self._constraint_keys}
        )

    # * COORDINATE TRANSFORMATION. ────────────────────────────────────
    def _force_type_or_error(
        self,
        bound_method: _collections.abc.Callable,
        targ_typ: type[BaseCoordinate],
        **constraints: bool,
    ) -> BaseCoordinate:
        cand = bound_method()
        if isinstance(cand, targ_typ):
            return cand
        reconstrained = self.with_constraints(**constraints)
        cand = bound_method.__func__(reconstrained)
        if isinstance(cand, targ_typ):
            return cand
        else:
            raise _exceptions.MalformedCoordinate(
                f"Location is not compatible with `{targ_typ.__name__}`: "
                f"{reconstrained}"
            )

    @staticmethod
    @_functools.cache
    def _get_conversion_sequence(
        targ_type: type[BaseCoordinate],
    ) -> tuple[_ToMethod | None, _ToMethod]:
        if targ_type is LatLonPoint:
            return (None, BaseCoordinate.to_latlon)
        if targ_type in (LpsPoint, LtmPoint):
            convert = BaseCoordinate.to_lps_or_ltm
        elif targ_type in (LpsLgrsBox, LtmLgrsBox):
            convert = BaseCoordinate.to_lgrs
        elif targ_type in (LpsAccBox, LtmAccBox):
            convert = BaseCoordinate.to_acc
        else:
            BaseCoordinate._raise_unexpected()
        if targ_type.is_lps_based():
            force_system = BaseCoordinate.to_lps
        elif targ_type.is_ltm_based():
            force_system = BaseCoordinate.to_ltm
        else:
            BaseCoordinate._raise_unexpected()
        return (force_system, convert)

    def to(
        self, typ: type[BaseCoordinate], *, any_system: bool = False
    ) -> BaseCoordinate:
        """
        Transform `self` to the specified coordinate type.

        This is a convenience function to call one or two `._to_*()`s in
        series. See Examples.

        Parameters
        ----------
        typ : a BaseCoordinate subclass
            The coordinate type to which `self` should be converted.
        any_system : bool, default=False
            Whether to allow the output coordinate to be from either system
            (LPS or LTM).

        Returns
        -------
        coord : BaseCoordinate (specifically, `typ`)
            The transformed coordinate. If `self` is compatible, `self` is
            returned. If caching is enabled, a cached instance may be returned.

        Raises
        ------
        lgrs.Exceptions.MalformedCoordinate
            If `any_system=False` and the system of `typ` is incompatible with
            `self`.

        Examples
        --------
        >>> lat_lon_point = LatLonPoint(0, 0)
        >>> new = lat_lon_point.to(LtmLgrsBox)  # Transform 1
        >>> isinstance(new, LtmLgrsBox)
        True

        In this case, transformation is exact.

        >>> new.distance_to(lat_lon_point)
        0.0

        You can also relax system requirements.

        >>> new_2 = lat_lon_point.to(LpsLgrsBox, any_system=True)  # Transform 2
        >>> isinstance(new_2, LtmLgrsBox)
        True

        Transform 1 is equivalent to::

            lat_lon_point.to_lps().to_lgrs()

        and Transform 2 is equivalent to::

            lat_lon_point.to_lgrs()
        """  # noqa: E501
        force_system, convert = self._get_conversion_sequence(typ)
        if (
            not any_system
            and force_system is not None
            and (
                isinstance(self, LatLonPoint)
                or self.is_lps_based() != typ.is_lps_based()
            )
        ):
            basis = force_system(self)
        else:
            basis = self
        return convert(basis)

    @_redirect
    def to_acc(self) -> LpsAccBox | LtmAccBox:
        """
        Transform coordinate to `LpsAccBox` or `LtmAccBox`.

        The type of `out` is determined by the combination of
        `self.constraints` and the location of `self` on the Moon.

        `out` is not validated with this call but should be valid if `self` is
        valid.

        Returns
        -------
        out : LpsAccBox or LtmAccBox
            The transformed coordinate. If `self` is compatible, `self` is
            returned. If caching is enabled, a cached instance may be returned.
        """

    @_redirect
    def to_latlon(self) -> LatLonPoint:
        """
        Transform coordinate to `LatLonPoint`.

        `out` is not validated with this call but should be valid if `self` is
        valid.

        Returns
        -------
        out : LatLonPoint
            The transformed coordinate. If `self` is compatible, `self` is
            returned. If caching is enabled, a cached instance may be returned.
        """

    @_redirect
    def to_lgrs(self) -> LpsLgrsBox | LtmLgrsBox:
        """
        Transform coordinate to `LpsLgrsBox` or `LtmLgrsBox`.

        The type of `out` is determined by the combination of
        `self.constraints` and the location of `self` on the Moon.

        `out` is not validated with this call but should be valid if `self` is
        valid.

        Returns
        -------
        out : LpsLgrsBox or LtmLgrsBox
            The transformed coordinate. If `self` is compatible, `self` is
            returned. If caching is enabled, a cached instance may be returned.
        """

    def to_lps(self) -> LpsPoint:
        """
        Transform coordinate to `LpsPoint`, if allowed.

        The constraints of `out` will differ from those of `self` if necessary
        to support the LPS system.

        Returns
        -------
        out : LpsPoint
            The transformed coordinate. If `self` is compatible, `self` is
            returned. If caching is enabled, a cached instance may be returned.

        Raises
        ------
        lgrs.Exceptions.MalformedCoordinate
            If the location of `self` on the Moon is outside the LPS region
            supported by LGRS.
        """
        lps_point = self._force_type_or_error(
            self.to_lps_or_ltm,
            LpsPoint,
            prefer_lps=True,
            extended_ltm=False,
            global_ltm=False,
        )
        return lps_point

    @_redirect
    def to_lps_or_ltm(self) -> LpsPoint | LtmPoint:
        """
        Transform coordinate to `LpsPoint` or `LtmPoint`.

        The type of `out` is determined by the combination of
        `self.constraints` and the location of `self` on the Moon.

        `out` is not validated with this call but should be valid if `self` is
        valid.

        Returns
        -------
        out : LpsPoint or LtmPoint
            The transformed coordinate. If `self` is compatible, `self` is
            returned. If caching is enabled, a cached instance may be returned.
        """

    def to_ltm(self) -> LtmPoint:
        """
        Transform coordinate to `LtmPoint`.

        The constraints of `out` will differ from those of `self` if necessary
        to support the LTM system.

        Returns
        -------
        out : LtmPoint
            The transformed coordinate. If `self` is compatible, `self` is
            returned. If caching is enabled, a cached instance may be returned.
        """
        ltm_point = self._force_type_or_error(
            self.to_lps_or_ltm, LtmPoint, global_ltm=True
        )
        return ltm_point

    # Note: The following four methods permit `._to_*()` methods to be
    # defined in subclasses for just one step in each direction.
    def _to_acc(self) -> LpsAccBox | LtmAccBox:
        if isinstance(self, (LpsPoint, LtmPoint)):
            lps_or_ltm = self
        else:
            assert isinstance(self, LatLonPoint)
            lps_or_ltm = self._to_lps_or_ltm()
        lgrs = lps_or_ltm._to_lgrs()
        acc = lgrs._to_acc()
        return acc

    def _to_latlon(self) -> LatLonPoint:
        if isinstance(self, (LpsLgrsBox, LtmLgrsBox)):
            lgrs = self
        else:
            assert isinstance(self, (LpsAccBox, LtmAccBox))
            lgrs = self._to_lgrs()
        lps_or_ltm = lgrs._to_lps_or_ltm()
        latlon = lps_or_ltm._to_latlon()
        return latlon

    def _to_lgrs(self) -> LpsLgrsBox | LtmLgrsBox:
        assert isinstance(self, LatLonPoint)
        lps_or_ltm = self._to_lps_or_ltm()
        lgrs = lps_or_ltm._to_lgrs()
        return lgrs

    def _to_lps_or_ltm(self) -> LpsPoint | LtmPoint:
        assert isinstance(self, (LpsAccBox, LtmAccBox))
        lgrs = self._to_lgrs()
        lps_or_ltm = lgrs._to_lps_or_ltm()
        return lps_or_ltm

    # * UTILITIES. ────────────────────────────────────────────────────
    def _iter_value_strings(self) -> _typing.Iterator[str]:
        for value in self:
            match value:
                case str():
                    yield value
                case bool() | None:
                    continue
                case int() | float():
                    yield repr(value)
                case _:
                    self._raise_unexpected()


# endregion
###############################################################################
# region> POINT COORDINATE TYPES
###############################################################################
class PointCoordinate(BaseCoordinate):
    """The base class for all point coordinates."""

    # * COORDINATE TRANSFORMATION. ────────────────────────────────────
    @_abc.abstractmethod
    def _get_proj_crs(self, **kwargs) -> _srs.CRS: ...

    @staticmethod
    @_caching._optionally_cache
    def _get_transformer(
        *, to_geographic: bool, proj_crs: _srs.CRS
    ) -> _pyproj.Transformer:
        geo_crs = _srs.make_lunar_crs()
        if to_geographic:
            crs_from = proj_crs
            crs_to = geo_crs
        else:
            crs_from = geo_crs
            crs_to = proj_crs
        transformer = _pyproj.Transformer.from_crs(crs_from, crs_to)
        return transformer


# TODO: Un-skip Example 3 once complete validation is implemented.
@_easy_dataclass
class LatLonPoint(PointCoordinate):
    """
    Create an instance representing a latitude-longitude point.

    The final four parameters--`prefer_lps`, `extended_ltm`, `global_ltm`,
    and `validate`--are common to all coordinates classes. The first three
    are called "constraints" (e.g., `.constraints`). Together, they
    partition the lunar surface into discrete regions that support either
    the Lunar Polar Stereographic (LPS) or Lunar Transverse Mercator (LTM)
    system. Once set, these constraints are honored in all derived
    coordinate instances (Example 1), except where explicitly overridden
    (Example 3). Conceptually, `extended_ltm` determines the maximum
    poleward extent of the LTM region and `prefer_lps` determines how the
    LPS-LTM overlap immediately equatorward of that boundary is handled. In
    the `global_ltm=True` case, the LTM region is global, so there is no LPS
    region.

    Parameters
    ----------
    latitude : float
        The latitude of `new`, in decimal degrees.
    longitude : float
        The longitude of `new`, in decimal degrees.
    prefer_lps : bool, default=False
        Whether to prefer the LPS system for a location where both LPS
        and LTM systems are supported by `lgrs`. This overlap only occurs
        slightly equatorward of the nominal latitudinal boundary between
        the systems, as determined by `extended_ltm`.
    extended_ltm : bool, default=False
        Whether to use the extended LTM region. If `True`, the nominal
        poleward extent of the LTM region is 82° N/S instead of 80° N/S.
        This nominal extent can be modified by `prefer_lps`.
    global_ltm : bool, default=False
        Whether to extend the LTM region globally. If `True`, there is no
        LPS region. If this option is enabled, enabling `prefer_lps` and/or
        `extended_ltm` will render the instance invalid.
    validate : bool, default=True
        Whether to validate that the coordinate's values are supported,
        subject to the constraints. This validation also conforms any
        values, where appropriate. See Example 5.

    Raises
    ------
    lgrs.Exceptions.MalformedCoordinate
        If the instance is invalid. Both values and constraints are
        considered.

    Examples
    --------
    >>> point = LatLonPoint(0, 0)

    Constraints are remembered and honored by all derived coordinate
    instances (except where explicitly overridden). Thus, even though the
    `extended_ltm` constraint is irrelevant to `geo_point` (below), that
    constraint is remembered and determines that `proj_point` belongs to the
    extended LTM region rather than the LPS region.

    >>> geo_point = LatLonPoint(81, 0, extended_ltm=True)
    >>> proj_point = geo_point.to_lps_or_ltm()  # Example 1
    >>> isinstance(proj_point, LtmPoint)
    True

    A coordinate may be invalid because its values are disallowed
    universally (Example 2) or because its type or values are disallowed by
    the applied constraints (Example 3). Conflicting constraints also render
     a coordinate invalid (Example 4).

    >>> LatLonPoint(1000, -1000)  # Example 2  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
      ...
    lgrs.exceptions.MalformedCoordinate:
      ...
    >>> ltm_point = geo_point.to_ltm()
    >>> ltm_point.with_constraints(extended_ltm=False)  # Example 3  # doctest: +SKIP
    Traceback (most recent call last):
      ...
    lgrs.exceptions.MalformedCoordinate:
      ...
    >>> LatLonPoint(0, 0, prefer_lps=True, global_ltm=True)  # Example 4  # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
      ...
    lgrs.exceptions.MalformedCoordinate:
      ...

    Finally, validation may conform values where those can be confidently
    interpreted.

    >>> latlon_point = LatLonPoint(45, 182)  # Example 5
    >>> latlon_point.longitude == -178  # Conformed.
    True
    """  # noqa: E501

    # * FIELDS AND VALIDATION. ────────────────────────────────────────
    latitude: float
    longitude: float

    def _template(self) -> str:
        if self.latitude >= 0:
            n_or_s = "N"
        else:
            n_or_s = "S"
        if self.longitude >= 0:
            e_or_w = "E"
        else:
            e_or_w = "W"
        return (
            f"{abs(self.latitude)!r}°{n_or_s} "
            f"{abs(self.longitude)!r}°{e_or_w}"
        )

    def _validate_latitude(self) -> float:
        (conformed_lat,) = _database._conform_latitudes((self.latitude,))
        return conformed_lat

    def _validate_longitude(self) -> float:
        (conformed_lon,) = _database._conform_longitudes((self.longitude,))
        return conformed_lon

    # * COORDINATE TRANSFORMATION. ────────────────────────────────────
    def _get_proj_crs(self, **kwargs) -> _srs.CRS:
        (long_name,) = _database._get_lunar_crs_long_names(
            conformed_latitudes=(self.latitude,),
            conformed_longitudes=(self.longitude,),
            **kwargs,
        )
        crs_info = _database.LunarCrsInfo._from_long_name(long_name)
        crs = crs_info.get_crs()
        return crs

    @_cache_new_cousin
    def _to_lps_or_ltm(self, *, allow_lps: bool = True) -> LpsPoint | LtmPoint:
        # Determine projected CRS.
        proj_crs = self._get_proj_crs(
            extended_ltm=self.extended_ltm, global_ltm=self.global_ltm
        )
        # TODO: Determine minimum absolute latitude for which conversion
        #  to LPS should be attempted.
        force_lps_attempt = (
            self.prefer_lps and allow_lps and proj_crs.lps_hemisphere is None
        )
        if force_lps_attempt:
            # *REASSIGNMENT*
            proj_crs = _srs.make_lunar_crs("S" if self.latitude < 0 else "N")

        # Transform.
        transformer = self._get_transformer(
            to_geographic=False, proj_crs=proj_crs
        )
        e, n = transformer.transform(self.latitude, self.longitude)

        # Create and return instance.
        if proj_crs.ltm_zone is None:
            try:
                lps = LpsPoint(
                    hemisphere=proj_crs.lps_hemisphere,
                    easting=e,
                    northing=n,
                    **self._root.constraints,
                    validate=force_lps_attempt,
                )
            except _exceptions.MalformedCoordinate:
                if force_lps_attempt:
                    # Note: `Lps` instance was invalid, so resort to
                    # `Ltm`.
                    return self._to_lps_or_ltm(allow_lps=False)
                raise
            return lps
        else:
            # TODO: Let Mark know that Table 2 is missing zones 24 and
            #  25.
            zone = int(proj_crs.ltm_zone[:-1])
            hemi = proj_crs.ltm_zone[-1]
            ltm = LtmPoint(
                zone_number=zone,
                hemisphere=hemi,
                easting=e,
                northing=n,
                **self._root.constraints,
                validate=False,
            )
            return ltm


@_easy_dataclass
class LpsPoint(PointCoordinate):
    """
    Create an instance representing a Lunar Polar Stereographic (LPS) point.

    Parameters
    ----------
    hemisphere : {"N", "S"}
        The point's hemisphere.
    easting : float
        The point's easting (meters).
    northing : float
        The point's northing (meters).
    prefer_lps : bool, default=False
        See `LatLonPoint` documentation.
    extended_ltm : bool, default=False
        See `LatLonPoint` documentation.
    global_ltm : bool, default=False
        See `LatLonPoint` documentation.
    validate : bool, default=True
        See `LatLonPoint` documentation.

    Raises
    ------
    lgrs.Exceptions.MalformedCoordinate
        If the instance is invalid. Both values and constraints are
        considered.

    Examples
    --------
    >>> point = LpsPoint("N", 500_000, 500_000)
    """

    # * FIELDS AND VALIDATION. ────────────────────────────────────────
    _template = "{hemisphere}{easting!r}E{northing!r}N"
    hemisphere: str
    easting: float
    northing: float

    # Note: `._validate_hemisphere()` is defined on base class.

    def _validate_easting(self) -> None:
        # TODO: Implement, with consideration of `.prefer_lps`, etc.
        # Note: Limits from reference code, adapted from p. 54 of M2025.
        return self._validate_against_closed_interval(
            attr_name="easting", minimum=197_000, maximum=805_000
        )

    def _validate_northing(self) -> None:
        # TODO: Implement, with consideration of `.prefer_lps`, etc.
        # Note: Limits from reference code, adapted from p. 54 of M2025.
        return self._validate_against_closed_interval(
            attr_name="northing", minimum=197_000, maximum=805_000
        )

    # * COORDINATE TRANSFORMATION. ────────────────────────────────────
    def _get_proj_crs(self) -> _srs.CRS:
        return _srs.make_lunar_crs(self.hemisphere)

    def _get_transformer(self, *, to_geographic: bool) -> _pyproj.Transformer:
        proj_crs = self._get_proj_crs()
        transformer = LatLonPoint._get_transformer(
            to_geographic=to_geographic, proj_crs=proj_crs
        )
        return transformer

    @_cache_new_cousin
    def _to_latlon(self) -> LatLonPoint:
        transformer = self._get_transformer(to_geographic=True)
        lat, lon = transformer.transform(self.easting, self.northing)
        latlon = LatLonPoint(
            latitude=lat,
            longitude=lon,
            **self._root.constraints,
            validate=False,
        )
        return latlon

    @_cache_new_cousin
    def _to_lgrs(self) -> LpsLgrsBox:
        is_in_west_half = self.easting < _wkt.LPS_FALSE_EASTING
        match (self.hemisphere, is_in_west_half):
            case ("S", True):  # Eq. 100
                lon_band = "A"
            case ("S", False):  # Eq. 101
                lon_band = "B"
            case ("N", True):  # Eq. 100
                lon_band = "Y"
            case ("N", False):  # Eq. 101
                lon_band = "Z"
            case _:
                self._raise_unexpected(self._validate_hemisphere)
        e_adj = self.easting - _wkt.LPS_FALSE_EASTING  # Eq. 109
        n_adj = self.northing - _wkt.LPS_FALSE_NORTHING  # Eq. 110
        if is_in_west_half:
            # TODO: Check with Mark that abs() should instead be around
            #  around e_adj in Eq. 103, as it is on line 1646 of
            #  reference code.
            # TODO: Let Mark know that Eq. 103 treats Table 13 as 1-
            #  indexed but Eq. 102 treats it as 0-indexed.
            # Note: Eq. 103 uses "24" but "23" used here since our Table
            # 13 equivalent starts at 1, not 0.
            ea_idx = 23 - _floor(abs(e_adj) // 25_000)  # Eq. 103
        else:
            ea_idx = _floor(e_adj // 25_000)  # Eq. 102
        ea = LpsLgrsBox._easting_area_chars[ea_idx]  # Tables 13, 14
        na_idx = _floor(n_adj // 25_000) + 13  # Eq. 104
        na = LpsLgrsBox._northing_area_chars[na_idx]  # Tables 15, 16
        if is_in_west_half:
            e = 25_000 - (abs(e_adj) % 25_000)  # Eq. 105
        else:
            e = e_adj % 25_000  # Eq. 106
        n = n_adj % 25_000
        lps_lrgs = LpsLgrsBox(
            longitudinal_band=lon_band,
            easting_area=ea,
            northing_area=na,
            easting=_format_as_five_digit_int(e),
            northing=_format_as_five_digit_int(n),
            **self._root.constraints,
            validate=False,
        )
        return lps_lrgs


@_easy_dataclass
class LtmPoint(PointCoordinate):
    """
    Create an instance representing a Lunar Transverse Mercator (LTM) point.

    Parameters
    ----------
    zone_number : int
        The LTM zone number, between 1 and 45 (inclusive).
    hemisphere : {"N", "S"}
        The point's hemisphere.
    easting : float
        The point's easting (meters).
    northing : float
        The point's northing (meters).
    prefer_lps : bool, default=False
        See `LatLonPoint` documentation.
    extended_ltm : bool, default=False
        See `LatLonPoint` documentation.
    global_ltm : bool, default=False
        See `LatLonPoint` documentation.
    validate : bool, default=True
        See `LatLonPoint` documentation.

    Raises
    ------
    lgrs.Exceptions.MalformedCoordinate
        If the instance is invalid. Both values and constraints are
        considered.

    Examples
    --------
    >>> point = LtmPoint(23, "N", 250_000, 250_000)
    """

    # * FIELDS AND VALIDATION. ────────────────────────────────────────
    _template = "{zone_number}{hemisphere}{easting!r}E{northing!r}N"
    zone_number: int
    hemisphere: str
    easting: float
    northing: float

    def _validate_zone_number(self) -> None:
        return self._validate_against_closed_interval(
            attr_name="zone_number", minimum=1, maximum=45
        )

    _validate_hemisphere = LpsPoint._validate_hemisphere

    def _validate_easting(self) -> None:
        # TODO: Confirm limits empirically.
        # Note: Limits from p. 47 of M2025.
        return self._validate_against_closed_interval(
            attr_name="easting", minimum=125_000, maximum=375_000
        )

    def _validate_northing(self) -> None:
        # TODO: Confirm limits empirically, including for extended and
        #  polar LTM. Note that reference code uses [0, 2_500_000].
        # Note: Limits from p. 47 of M2025.
        match self.hemisphere:
            case "N":
                minimum = 0
                maximum = 2_487_500
            case "S":
                minimum = 12_500
                maximum = 2_500_000
            case _:
                self._raise_unexpected(self._validate_hemisphere)
        return self._validate_against_closed_interval(
            attr_name="northing", minimum=minimum, maximum=maximum
        )

    # * COORDINATE TRANSFORMATION. ────────────────────────────────────
    def _get_proj_crs(self) -> _srs.CRS:
        return _srs.make_lunar_crs(f"{self.zone_number}{self.hemisphere}")

    _get_transformer = LpsPoint._get_transformer

    _to_latlon = LpsPoint._to_latlon

    @_cache_new_cousin
    def _to_lgrs(self) -> LtmLgrsBox:
        lon_band = self.zone_number
        lat_lon = self.to_latlon()
        lat_band_idx = _floor(lat_lon.latitude // 8)  # Eq. 81
        # Note: "+ 11" adjusts for indices in Table 6, which start at
        # -11.
        # Table 6
        lat_band = LtmLgrsBox._latitudinal_band_chars[lat_band_idx + 11]
        ea_idx = _floor(self.easting // 25_000) - 5  # Eq. 82
        ea = LtmLgrsBox._easting_area_chars[ea_idx]  # Table 7
        na_letterset = _calc_na_letterset(self.zone_number)  # Eq. 83
        na_idx = _floor(self.northing // 25_000) % 20  # Eq. 84
        na = LtmLgrsBox._northing_area__letterset_to_chars[na_letterset][
            na_idx
        ]  # Tables 8, 9, 10
        e = self.easting % 25_000  # Eq. 85
        n = self.northing % 25_000  # Eq. 86
        ltm_lgrs = LtmLgrsBox(
            longitudinal_band=lon_band,
            latitudinal_band=lat_band,
            easting_area=ea,
            northing_area=na,
            easting=_format_as_five_digit_int(e),
            northing=_format_as_five_digit_int(n),
            **self._root.constraints,
            validate=False,
        )
        return ltm_lgrs


# endregion
###############################################################################
# region> BOX COORDINATE BASE TYPES
###############################################################################
class BoxCoordinate(BaseCoordinate):
    """The base class for all gridded box coordinates."""

    # * FIELDS AND VALIDATION. ────────────────────────────────────────
    easting: str | None
    northing: str | None

    def _validate(self) -> None:
        super()._validate()
        self._validate_against_pattern()

    def _validate_against_pattern(self) -> None:
        if self._pattern.search(self.string) is None:
            raise _exceptions.MalformedCoordinate(
                f"`.string` does not have the form: {self._pattern.pattern!r}"
            )

    # * UTILITIES. ────────────────────────────────────────────────────
    @staticmethod
    def _as_int(string: str | None, *, nom_length: int) -> int:
        if string is None:
            return 0
        else:
            return int(f"{string}00"[:nom_length])

    # * INSTANTIATION FROM STRING. ────────────────────────────────────
    _pattern: _regex.Pattern

    @classmethod
    def from_string(
        cls, string: str, *, validate: bool = True
    ) -> _typing.Self:
        """
        Create a box coordinate instance from a string.

        Parameters
        ----------
        string : str
            The string form of the box coordinate, equivalent to `new.string`.
        validate : bool, default=True
            Whether to validate `new`.

        Returns
        -------
        new : BoxCoordinate
            The new box coordinate instance. The type is determined by the
            call. See Examples.

        Examples
        --------
        When called the `BoxCoordinate` base class, an instance of the
        appropriate type is returned.

        >>> box_1 = BoxCoordinate.from_string("12SAM1234512345")
        >>> isinstance(box_1, LtmLgrsBox)
        True

        When called from any other class (or instance), an instance of the same
        type is returned, if possible, or an error is raised.

        >>> box_2 = LtmLgrsBox.from_string("12SAM1234512345")
        >>> box_1 == box_2
        True
        >>> box_3 = LpsLgrsBox.from_string("12SAM1234512345")  # doctest: +IGNORE_EXCEPTION_DETAIL
        Traceback (most recent call last):
          ...
        lgrs.exceptions.MalformedCoordinate:
          ...
        """  # noqa: E501
        # Support call from `BoxCoordinate` itself.
        if cls is BoxCoordinate:
            for typ in (LpsLgrsBox, LpsAccBox, LtmLgrsBox, LtmAccBox):
                try:
                    new = typ.from_string(string)
                except _exceptions.MalformedCoordinate:
                    continue
                else:
                    return new
            raise _exceptions.MalformedCoordinate(
                f"`string` is not in a supported format: {string!r}"
            )

        # Match to pattern.
        match = cls._pattern.search(string)
        if match is None:
            raise _exceptions.MalformedCoordinate(
                f"`string` {string!r} is not in the supported format: "
                f"{cls._pattern.pattern!r}"
            )
        match_dict = match.groupdict()

        # Coerce each argument to the correct type.
        # TODO: Approach below allows 0-prefixing of integers. The only
        #  pattern that allows an ambiguity is for the first few
        #  characters of `Ltm*Box`. For example, should both "01N" and
        #  "1N" be allowed? The former has the benefit of ensuring that
        #  all strings have the same length, but `.string` uses the
        #  latter, which I think is Mark's intent. The reference code
        #  allows "1N", "01N", "001N", etc.
        field_name_to_type = cls._get_field_name_to_type()
        init_kwargs = {
            name: field_name_to_type[name](value_string)
            for name, value_string in match_dict.items()
            if value_string is not None
        }
        return cls(**init_kwargs, validate=validate)

    # * REFERENCE POINTS. ─────────────────────────────────────────────
    def _make_reference_point(
        self, easting_delta: float, northing_delta: float
    ) -> LatLonPoint:
        lps_or_ltm_point = self.to_lps_or_ltm()
        temp = lps_or_ltm_point.replace(
            easting=lps_or_ltm_point.easting + easting_delta,
            northing=lps_or_ltm_point.northing + northing_delta,
            validate=False,
        )
        # Note: New instance must be `LatLonPoint`, to be guaranteed
        # valid, and must be a copy, to divorce its cache history from
        # the possibly invalid `temp`.
        new = temp.to_latlon().copy()
        return new

    @_functools.cached_property
    def center_latlon(self) -> LatLonPoint:
        """The grid center as a `LatLonPoint`."""
        half_precision = 0.5 * self.precision
        center = self._make_reference_point(+half_precision, +half_precision)
        return center

    # * PUBLIC DATA AND METHODS. ──────────────────────────────────────
    def contains(
        self,
        other: BaseCoordinate,
        *,
        logical: bool = False,
        cross_system: bool = True,
    ) -> bool:
        """
        Test whether the areal extent of `self` includes another coordinate.

        More precisely, evaluate whether the interior of `self` includes the
        interior of `other`. Note that for non-logical (`logical=False`)
        evaluations, if `other` is extremely close to the boundary of `self`,
        the underlying transformation calculation may not be sufficiently
        precise to provide the correct result.

        Parameters
        ----------
        other : BaseCoordinate
            The possibly contained coordinate.
        logical : bool, default=False
            Whether to require logical containment. If `True`, and `other` is
            either not a box coordinate or from a different system (LPS or
            LTM), `False` is returned.
        cross_system : bool, default=True
            Whether to allow cross-system containment. If `False`, and `other`
            is from a different system (LPS or LTM), `False` is returned.

        Returns
        -------
        is_contained : bool
            Whether `other` is contained within `self`.
        """
        # Honor restrictive arguments.
        if logical and not isinstance(other, BoxCoordinate):
            return False
        if (logical or not cross_system) and (
            isinstance(other, LatLonPoint)
            or self.is_lps_based() != other.is_lps_based()
        ):
            return False

        # TODO: Should reimplement to project to LPS or LTM and then
        #  check whether within ranges. This neatly addresses otherwise
        #  complicate border situations (between LTM zones, between LPS
        #  and LTM regions). But keep current code to support "logical"
        #  use. Also, in cross-system case, will need to consider
        #  corners at least. (Current thinking is only corners and
        #  document this, in case that's not strictly sufficient.)
        # Coerce `other` to same type as `self`.
        try:
            other_box = other.to(type(self))
        except _exceptions.MalformedCoordinate:
            return False

        # If `other` is larger than `self`, `self` cannot contain
        # `other`.
        if other_box.precision > self.precision:
            return False

        # Test whether `other`, expanded to the same size as `self`, is
        # equivalent to `self`.
        return self.is_equal_to(other_box.truncate(self.precision))

    @_functools.cached_property
    def precision(self) -> int:
        """
        The precision of the coordinate, in meters.

        Strictly, this precision is expressed in grid meters and therefore
        inherits the distortion of the underlying system (LPS or LTM).
        """
        lgrs_easting = self.to_lgrs().easting
        # Table 11
        if lgrs_easting is None:
            return 25_000
        match len(lgrs_easting):
            case 5:
                return 1
            case 4:
                return 10
            case 3:
                return 100
            case 2:
                return 1000
            case _:
                self._raise_unexpected()

    def truncate(
        self, min_precision: float, *, copy: bool = False
    ) -> _typing.Self:
        """
        Truncate (or extend) the coordinate to represent a minimum precision.

        More precisely, the respective lengths of the relevant easting and
        northing strings will be truncated, or extended with zeros, as
        necessary so that `out.precision` is greater than or equal to
        `min_precision`. The final lengths of these strings will be no longer
        than what is strictly necessary to satisfy `min_precision`.

        Parameters
        ----------
        min_precision : float
            The minimum allowed value of `out.precision`.
        copy : bool, default=False
            Whether to ensure that `out` is not `self`. If `False` and `self`
            is suitable, it is returned as `out`.

        Returns
        -------
        out : typing.Self
            A truncated or extended version, as appropriate.
        """
        # Determine `*LgrsBox` easting and northing character count.
        if min_precision < 1:
            raise TypeError(
                f"`min_precision` must be >= 1, not: {min_precision!r}"
            )
        elif 1 <= min_precision < 10:
            lgrs_char_count = 5
        elif 10 <= min_precision < 100:
            lgrs_char_count = 4
        elif 100 <= min_precision < 1000:
            lgrs_char_count = 3
        elif 1000 <= min_precision < 25_000:
            lgrs_char_count = 2
        else:
            lgrs_char_count = 0

        # Return `self`, if allowed and suitable.
        self_lgrs_box = self.to_lgrs()
        if not copy and len(_as_str(self_lgrs_box.easting)) == lgrs_char_count:
            return self

        # Create and return truncated instance.
        init_kwargs = self_lgrs_box._init_kwargs.copy()
        if lgrs_char_count:
            easting = _as_str(self_lgrs_box.easting)
            northing = _as_str(self_lgrs_box.northing)
            init_kwargs["easting"] = f"{easting}00000"[:lgrs_char_count]
            init_kwargs["northing"] = f"{northing}00000"[:lgrs_char_count]
        else:
            init_kwargs["easting"] = None
            init_kwargs["northing"] = None
        # TODO: Consider how to handle the possibility that a truncated
        #  LPS-based coordinate now plots outside the `prefer_lps=False`
        #  zone. Simplest solution would be to assign `prefer_lps=True`
        #  for any LPS-based coordinate upon truncation, but that might
        #  not be what the user expects.
        new_lgrs_box = type(self_lgrs_box)(**init_kwargs, validate=False)
        final = new_lgrs_box.to(type(self))
        return final


class _BaseAccBox(BoxCoordinate):
    _condensed_prefix_template: str

    @_functools.cached_property
    def _easting_int(self) -> int:
        return self._as_int(self.easting, nom_length=3)

    @_functools.cached_property
    def _northing_int(self) -> int:
        return self._as_int(self.northing, nom_length=3)

    @_functools.cached_property
    def condensed(self) -> str:
        return self.string.removeprefix(self.condensed_prefix)

    @_functools.cached_property
    def condensed_prefix(self) -> str:
        prefix = self._condensed_prefix_template.format(**self._init_kwargs)
        return prefix


class _BaseLgrsBox(BoxCoordinate):

    @_functools.cached_property
    def _easting_int(self) -> int:
        return self._as_int(self.easting, nom_length=5)

    @_functools.cached_property
    def _northing_int(self) -> int:
        return self._as_int(self.northing, nom_length=5)


# endregion
###############################################################################
# region> BOX COORDINATE TYPES
###############################################################################
# TODO: Think about what best field names are, e.g., `easting_area`,
#  `easting_25k`, `easting_25km`, `easting_25k_area`, or
#  `easting_25km_area`.
@_easy_dataclass
class LpsAccBox(_BaseAccBox):
    """
    Create an instance representing an LPS Artemis Condensed Coordinate box.

    Note that each instance represents a square area in LPS space, referenced
    to its lower-left (grid-southwest) corner.

    Except for `easting` and `northing`, each string argument is a single
    character.

    Parameters
    ----------
    longitudinal_band : {"A", "B", "Y", "Z"}
        The polar zone band, which subdivides each polar zone into an east and
        west area.
    easting_area : str
        The point's 25-kilometer-grid easting area designator.
    northing_area : str
        The point's 25-kilometer-grid northing area designator.
    easting_1k : str, optional
        The point's 1-kilometer-grid easting area designator.
    easting : str, optional
        The point's easting (meters).
    northing_1k : str, optional
        The point's 1-kilometer-grid northing area designator.
    northing : str, optional
        The point's northing (meters).
    prefer_lps : bool, default=False
        See `LatLonPoint` documentation.
    extended_ltm : bool, default=False
        See `LatLonPoint` documentation.
    global_ltm : bool, default=False
        See `LatLonPoint` documentation.
    validate : bool, default=True
        See `LatLonPoint` documentation.

    Raises
    ------
    lgrs.Exceptions.MalformedCoordinate
        If the instance is invalid. Both values and constraints are
        considered.

    Examples
    --------
    >>> box_1 = LpsAccBox(
    ...     longitudinal_band='B', easting_area='A', northing_area='N',
    ...     easting_1k='-', easting='000', northing_1k='-', northing='000'
    ... )

    You may find it simpler to instantiate from a string.

    >>> box_2 = LpsAccBox.from_string("BAN-000-000")
    >>> box_1 == box_2
    True
    """

    _condensed_prefix_template = (
        "{longitudinal_band}{easting_area}{northing_area}"
    )

    # * FIELDS AND VALIDATION. ────────────────────────────────────────
    _pattern = _compile_regex_without_i_and_o(
        "^"
        "(?P<longitudinal_band>[ABYZ])"
        "(?P<easting_area>[A-Z])"
        "(?P<northing_area>[-A-Z+])"
        "((?P<easting_1k>[-A-Z])"
        "(?P<easting>[0-9]{1,3})?"
        "(?P<northing_1k>[-A-Z])"
        "(?P<northing>[0-9]{1,3})?)?"
        "$"
    )
    longitudinal_band: str
    easting_area: str
    northing_area: str
    easting_1k: str | None = None
    easting: str | None = None
    northing_1k: str | None = None
    northing: str | None = None

    _validate_longitudinal_band = _return_none  # `._pattern` is sufficient.

    def _validate_easting_area(self) -> None:
        match self.longitudinal_band:
            case "A" | "Y":
                minimum = "M"
                maximum = "Z"
            case "B" | "Z":
                minimum = "A"
                maximum = "N"
            case _:
                self._raise_unexpected(self._validate_longitudinal_band)
        self._validate_against_closed_interval(
            attr_name="easting_area",
            minimum=minimum,
            maximum=maximum,
            if_attr_name="longitudinal_band",
        )

    _validate_northing_area = _return_none  # `._pattern` is sufficient.
    _validate_easting_1k = _return_none  # `._pattern` is sufficient.

    def _validate_easting(self) -> None:
        if (self.easting is None) != (self.northing is None):
            raise _exceptions.MalformedCoordinate(
                "`easting` and `northing` must both be specified "
                "or both be `None`."
            )

    _validate_northing_1k = _return_none  # `._pattern` is sufficient.
    _validate_northing = _return_none  # `._pattern` is sufficient.

    # * COORDINATE TRANSFORMATION. ────────────────────────────────────
    # Tables 13, 14
    _easting_area_chars = _extract_chars_from_pattern(_pattern, "easting_area")
    # Tables 15, 16
    _northing_area_chars = _extract_chars_from_pattern(
        _pattern, "northing_area"
    )
    # Table 17
    _easting_1k_chars = _extract_chars_from_pattern(_pattern, "easting_1k")
    _northing_1k_chars = _easting_1k_chars

    @_cache_new_cousin
    def _to_lgrs(self) -> LpsLgrsBox | LtmLgrsBox:
        if self.easting_1k is None:
            easting = None
            northing = None
        else:
            # Eqs. 91, 121, 122
            easting = f"{self._easting_1k_chars.index(self.easting_1k):02}"
            northing = f"{self._northing_1k_chars.index(self.northing_1k):02}"
            if self.easting is not None:
                easting += self.easting  # Eq. 123
                northing += self.northing  # Eq. 124
        init_kwargs = {
            "longitudinal_band": self.longitudinal_band,
            "easting_area": self.easting_area,
            "northing_area": self.northing_area,
            "easting": easting,
            "northing": northing,
        }
        if isinstance(self, LpsAccBox):
            lgrs_type = LpsLgrsBox
        else:
            lgrs_type = LtmLgrsBox
            init_kwargs["latitudinal_band"] = self.latitudinal_band
        lgrs = lgrs_type(
            **init_kwargs, **self._root.constraints, validate=False
        )
        return lgrs


@_easy_dataclass
class LpsLgrsBox(_BaseLgrsBox):
    """
    Create an instance representing an LPS Lunar Grid Reference System box.

    Note that each instance represents a square area in LPS space, referenced
    to its lower-left (grid-southwest) corner.

    Except for `easting` and `northing`, each string argument is a single
    character.

    Parameters
    ----------
    longitudinal_band : {"A", "B", "Y", "Z"}
        The polar zone band, which subdivides each polar zone into an east and
        west area.
    easting_area : str
        The point's 25-kilometer-grid easting area designator.
    northing_area : str
        The point's 25-kilometer-grid northing area designator.
    easting : str, optional
        The point's easting (meters).
    northing : str, optional
        The point's northing (meters).
    prefer_lps : bool, default=False
        See `LatLonPoint` documentation.
    extended_ltm : bool, default=False
        See `LatLonPoint` documentation.
    global_ltm : bool, default=False
        See `LatLonPoint` documentation.
    validate : bool, default=True
        See `LatLonPoint` documentation.

    Raises
    ------
    lgrs.Exceptions.MalformedCoordinate
        If the instance is invalid. Both values and constraints are
        considered.

    Examples
    --------
    >>> box_1 = LpsLgrsBox(
    ...     longitudinal_band='Z', easting_area='A', northing_area='B',
    ...     easting='12345', northing='12345'
    ... )

    You may find it simpler to instantiate from a string.

    >>> box_2 = LpsLgrsBox.from_string("ZAB1234512345")
    >>> box_1 == box_2
    True
    """

    # * FIELDS AND VALIDATION. ────────────────────────────────────────
    _pattern = _compile_regex_without_i_and_o(
        "^"
        "(?P<longitudinal_band>[ABYZ])"
        "(?P<easting_area>[A-Z])"
        "(?P<northing_area>[-A-Z+])"
        f"({_make_en_pattern(5, 4, 3, 2)})?"
        "$"
    )
    longitudinal_band: str
    easting_area: str
    northing_area: str
    easting: str | None = None
    northing: str | None = None

    _validate_longitudinal_band = LpsAccBox._validate_longitudinal_band
    _validate_easting_area = LpsAccBox._validate_easting_area
    _validate_northing_area = LpsAccBox._validate_northing_area

    def _validate_easting(self) -> None:
        # TODO: Implement, with consideration of `.prefer_lps`, etc.
        #  Should upper limit be 24_999?
        # Note: Limits from reference code.
        return self._validate_against_closed_interval(
            attr_name="easting", minimum=0, maximum=25_000, coerce_str=True
        )

    def _validate_northing(self) -> None:
        # TODO: Implement, with consideration of `.prefer_lps`, etc.
        #  Should upper limit be 24_999?
        return self._validate_against_closed_interval(
            attr_name="northing", minimum=0, maximum=25_000, coerce_str=True
        )

    # * COORDINATE TRANSFORMATION. ────────────────────────────────────
    _easting_area_chars = LpsAccBox._easting_area_chars
    _northing_area_chars = LpsAccBox._northing_area_chars

    @_cache_new_cousin
    def _to_acc(self) -> LpsAccBox | LtmAccBox:
        init_kwargs = {
            "longitudinal_band": self.longitudinal_band,
            "easting_area": self.easting_area,
            "northing_area": self.northing_area,
        }
        if self.easting is not None:
            init_kwargs["easting_1k"] = LpsAccBox._easting_1k_chars[
                int(self.easting[:2])
            ]
            init_kwargs["northing_1k"] = LpsAccBox._northing_1k_chars[
                int(self.northing[:2])
            ]
            if len(self.easting) > 2:
                init_kwargs["easting"] = self.easting[2:]
                init_kwargs["northing"] = self.northing[2:]
        if isinstance(self, LpsLgrsBox):
            acc_type = LpsAccBox
        else:
            acc_type = LtmAccBox
            init_kwargs["latitudinal_band"] = self.latitudinal_band
        acc = acc_type(**init_kwargs, **self._root.constraints, validate=False)
        return acc

    @_cache_new_cousin
    def _to_lps_or_ltm(self) -> LpsPoint:
        # Determine hemisphere and whether in the western half.
        # p. 92 (parags. 1, 3)
        match self.longitudinal_band:
            case "A":
                hemi = "S"
                is_in_west_half = True
            case "B":
                hemi = "S"
                is_in_west_half = False
            case "Y":
                hemi = "N"
                is_in_west_half = True
            case "Z":
                hemi = "N"
                is_in_west_half = False
            case _:
                self._raise_unexpected()

        # Calculate easting and northing.
        # Tables 13 + 14
        ea_idx = self._easting_area_chars.index(self.easting_area)
        if is_in_west_half:
            # Note: `self._easting_area_chars` is 0-indexed but Table 7
            # is 1-indexed, so "+ 1" in Eq. 112 is dropped here.
            ea_val = -25_000 * (24 - ea_idx)  # Eq. 112
        else:
            # TODO: Let Mark know.
            # Note: Although `self._easting_area_chars` is 0-indexed and
            # Table 7 is 1-indexed, Eq. 113 is exactly reproduced here.
            ea_val = 25_000 * ea_idx  # Eq. 113
        # Eq. 115
        easting = ea_val + self._easting_int + _wkt.LPS_FALSE_EASTING
        # Tables 15, 16
        na_idx = self._northing_area_chars.index(self.northing_area)
        na_val = 25_000 * (na_idx - 13)  # Eq. 114
        # Eq. 116
        northing = na_val + self._northing_int + _wkt.LPS_FALSE_NORTHING

        # Create and return instance.
        lps = LpsPoint(
            hemisphere=hemi,
            easting=easting,
            northing=northing,
            **self.constraints,
            validate=False,
        )
        return lps


@_easy_dataclass
class LtmAccBox(_BaseAccBox):
    """
    Create an instance representing an LTM Artemis Condensed Coordinate box.

    Note that each instance represents a square area in LTM space, referenced
    to its lower-left (grid-southwest) corner.

    Except for `easting` and `northing`, each string argument is a single
    character.

    Parameters
    ----------
    longitudinal_band : int
        The LTM zone number, between 1 and 45 (inclusive).
    latitudinal_band : str
        The latitudinal band.
    easting_area : str
        The point's 25-kilometer-grid easting area designator.
    northing_area : str
        The point's 25-kilometer-grid northing area designator.
    easting_1k : str, optional
        The point's 1-kilometer-grid easting area designator.
    easting : str, optional
        The point's easting (meters).
    northing_1k : str, optional
        The point's 1-kilometer-grid northing area designator.
    northing : str, optional
        The point's northing (meters).
    prefer_lps : bool, default=False
        See `LatLonPoint` documentation.
    extended_ltm : bool, default=False
        See `LatLonPoint` documentation.
    global_ltm : bool, default=False
        See `LatLonPoint` documentation.
    validate : bool, default=True
        See `LatLonPoint` documentation.

    Raises
    ------
    lgrs.Exceptions.MalformedCoordinate
        If the instance is invalid. Both values and constraints are
        considered.

    Examples
    --------
    >>> box_1 = LtmAccBox(
    ...     longitudinal_band=23, latitudinal_band='N',
    ...     easting_area='F', northing_area='F',
    ...     easting_1k='-', easting='000', northing_1k='-', northing='000'
    ... )

    You may find it simpler to instantiate from a string.

    >>> box_2 = LtmAccBox.from_string("23NFF-000-000")
    >>> box_1 == box_2
    True
    """

    _condensed_prefix_template = (
        "{longitudinal_band}{latitudinal_band}{easting_area}{northing_area}"
    )

    # * FIELDS AND VALIDATION. ────────────────────────────────────────
    _pattern = _compile_regex_without_i_and_o(
        "^"
        "(?P<longitudinal_band>[0-9]{1,2})"
        "(?P<latitudinal_band>[C-X])"
        "(?P<easting_area>[A-K])"
        "(?P<northing_area>[A-V])"
        "((?P<easting_1k>[-A-Z])"
        "(?P<easting>[0-9]{1,3})?"
        "(?P<northing_1k>[-A-Z])"
        "(?P<northing>[0-9]{1,3})?)?"
        "$"
    )
    longitudinal_band: int  # LTM zone
    latitudinal_band: str
    easting_area: str
    northing_area: str
    easting_1k: str
    easting: str | None
    northing_1k: str
    northing: str | None

    def _validate_longitudinal_band(self) -> None:
        return self._validate_against_closed_interval(
            attr_name="longitudinal_band", minimum=1, maximum=45
        )

    _validate_latitudinal_band = _return_none  # `._pattern` is sufficient.
    _validate_easting_area = _return_none  # `._pattern` is sufficient.

    def _validate_northing_area(self) -> None:
        na_letterset = _calc_na_letterset(self.longitudinal_band)  # Eq. 83
        na_chars = LtmLgrsBox._northing_area__letterset_to_chars[na_letterset]
        self._validate_against_sequence(
            attr_name="easting_area",
            sequence=na_chars,
            if_attr_name="longitudinal_band",
        )

    _validate_easting_1k = LpsAccBox._validate_easting_1k
    _validate_easting = LpsAccBox._validate_easting
    _validate_northing_1k = LpsAccBox._validate_northing_1k
    _validate_northing = LpsAccBox._validate_northing

    @property
    def zone_number(self) -> int:
        return self.longitudinal_band

    # * Coordinate transformation. ────────────────────────────────────
    # Table 6
    _latitudinal_band_chars = _extract_chars_from_pattern(
        _pattern, "latitudinal_band", pre="C", post="X"
    )
    # Table 7
    _easting_area_chars = _extract_chars_from_pattern(_pattern, "easting_area")
    # Tables 8-10
    _northing_area__letterset_to_chars = [
        "ABCDEFGHJKLMNPQRSTUV",
        "FGHJKLMNPQRSTUVABCDE",
        "LMNPQRSTUVABCDEFGHJK",
    ]
    _easting_1k_chars = LpsAccBox._easting_1k_chars
    _northing_1k_chars = LpsAccBox._northing_1k_chars

    _to_lgrs = LpsAccBox._to_lgrs


@_easy_dataclass
class LtmLgrsBox(_BaseLgrsBox):
    """
    Create an instance representing an LTM Lunar Grid Reference System box.

    Note that each instance represents a square area in LTM space, referenced
    to its lower-left (grid-southwest) corner.

    Except for `easting` and `northing`, each string argument is a single
    character.

    Parameters
    ----------
    longitudinal_band : int
        The LTM zone number, between 1 and 45 (inclusive).
    latitudinal_band : str
        The latitudinal band.
    easting_area : str
        The point's 25-kilometer-grid easting area designator.
    northing_area : str
        The point's 25-kilometer-grid northing area designator.
    easting : str, optional
        The point's easting (meters).
    northing : str, optional
        The point's northing (meters).
    prefer_lps : bool, default=False
        See `LatLonPoint` documentation.
    extended_ltm : bool, default=False
        See `LatLonPoint` documentation.
    global_ltm : bool, default=False
        See `LatLonPoint` documentation.
    validate : bool, default=True
        See `LatLonPoint` documentation.

    Raises
    ------
    lgrs.Exceptions.MalformedCoordinate
        If the instance is invalid. Both values and constraints are
        considered.

    Examples
    --------
    >>> box_1 = LtmLgrsBox(
    ...     longitudinal_band=12, latitudinal_band='S',
    ...     easting_area='A', northing_area='M',
    ...     easting='12345', northing='12345'
    ... )

    You may find it simpler to instantiate from a string.

    >>> box_2 = LtmLgrsBox.from_string("12SAM1234512345")
    >>> box_1 == box_2
    True
    """

    # * Fields and validation. ────────────────────────────────────────
    _pattern = _compile_regex_without_i_and_o(
        "^"
        "(?P<longitudinal_band>[0-9]{1,2})"
        "(?P<latitudinal_band>[C-X])"
        "(?P<easting_area>[A-K])"
        "(?P<northing_area>[A-V])"
        f"({_make_en_pattern(5, 4, 3, 2)})?"
        "$"
    )
    longitudinal_band: int  # LTM zone
    latitudinal_band: str
    easting_area: str
    northing_area: str
    easting: str | None = None
    northing: str | None = None

    _validate_longitudinal_band = LtmAccBox._validate_longitudinal_band
    _validate_latitudinal_band = LtmAccBox._validate_latitudinal_band
    _validate_easting_area = LtmAccBox._validate_easting_area
    _validate_northing_area = LtmAccBox._validate_northing_area
    _validate_easting = LpsLgrsBox._validate_easting
    _validate_northing = LpsLgrsBox._validate_northing

    zone_number = LtmAccBox.zone_number

    # * Coordinate transformation. ────────────────────────────────────
    _latitudinal_band_chars = LtmAccBox._latitudinal_band_chars
    _easting_area_chars = LtmAccBox._easting_area_chars
    _northing_area__letterset_to_chars = (
        LtmAccBox._northing_area__letterset_to_chars
    )

    _latitudinal_band_n_idx = _latitudinal_band_chars.index("N")

    @staticmethod
    @_functools.lru_cache(maxsize=5)  # `maxsize` is small but arbitrary.
    def _calc_n_band(lat_band_min: int) -> int:
        # Note: Longitude is arbitrary.
        temp_latlon = LatLonPoint(
            latitude=lat_band_min, longitude=0, validate=False
        )
        nband_float = temp_latlon.to_ltm().northing
        nband = _floor(nband_float // 25_000) * 25_000  # Eq. 96
        return nband

    _to_acc = LpsLgrsBox._to_acc

    @_cache_new_cousin
    def _to_lps_or_ltm(self) -> LtmPoint:
        # Determine hemisphere.
        # Eq. 92 (also Fig. 15)
        lat_band_idx = self._latitudinal_band_chars.index(
            self.latitudinal_band
        )
        if lat_band_idx >= self._latitudinal_band_n_idx:
            hemi = "N"
        else:
            hemi = "S"

        # Calculate easting and northing.
        ea_idx = self._easting_area_chars.index(self.easting_area)  # Table 7
        # TODO: Let Mark know.
        # Note: Although `self._easting_area_chars` is 0-indexed and
        # Table 7 is 1-indexed, Eq. 93 is exactly reproduced here.
        # TODO: Based on ref code (lines 1728-9), the parentheses are
        #  assumed to be around the first two values, unlike the order
        #  of operations in Eq. 93. Now confirmed. Let Mark know.
        ea_val = (5 + ea_idx) * 25_000  # Eq. 93
        easting = ea_val + self._easting_int  # Eq. 98
        na_letterset = _calc_na_letterset(self.longitudinal_band)  # Eq. 83
        # Tables 8-10
        na_idx = self._northing_area__letterset_to_chars[na_letterset].index(
            self.northing_area
        )
        na_val_rel = na_idx * 25_000  # Eq. 94
        # Table 6
        # TODO: Same comment as above about parentheses.
        # Eq. 95
        lat_band_min = (
            self._latitudinal_band_chars.index(self.latitudinal_band) - 11
        ) * 8
        nband = self._calc_n_band(lat_band_min)  # Eq. 96, etc.
        # Eqs. 97, 99
        na_val = 0  # Initialize.
        while True:
            northing = na_val + na_val_rel + self._northing_int
            if northing >= nband:
                break
            na_val += 500_000

        # Create and return instance.
        ltm = LtmPoint(
            zone_number=self.longitudinal_band,
            hemisphere=hemi,
            easting=easting,
            northing=northing,
            validate=False,
        )
        return ltm


# endregion


# TODO: Move to a proper test script.
if __name__ == "__main__":
    _caching.enable_caching(False)

    lat_lon = LatLonPoint(
        latitude=-30.13048481, longitude=96.48515138
    )  # p. 45
    lps_or_ltm = lat_lon.to_lps_or_ltm()
    lgrs_ = lps_or_ltm.to_lgrs()
    lgrs_.is_equal_to(LtmLgrsBox.from_string("35JFJ1271112229"), error=True)

    # lgrs_.to_latlon().is_equal_to(lat_lon, error=True)

    lat_lon1 = LatLonPoint(latitude=-81.13048481, longitude=96.48515138)
    lps_or_ltm1 = lat_lon1.to_lps_or_ltm()
    lgrs1 = lps_or_ltm1.to_lgrs()
    assert isinstance(lgrs1, LpsLgrsBox)

    lat_lon2 = lat_lon1.with_constraints(extended_ltm=True)
    lps_or_ltm2 = lat_lon2.to_lps_or_ltm()
    lgrs2 = lps_or_ltm2.to_lgrs()
    assert isinstance(lgrs2, LtmLgrsBox)

    lat_lon4 = LatLonPoint(
        latitude=-86.38231380366628, longitude=-6.004331982958013
    )  # p. 53, 64
    lps_or_ltm4 = lat_lon4.to_lps_or_ltm()
    lgrs4 = lps_or_ltm4.to_lgrs()
    assert lgrs4.is_equal_to(
        LpsLgrsBox.from_string("AZS1359008480"), error=True
    )

    lgrs4.to_latlon()

    lat_lon5 = LatLonPoint(latitude=-30.13048481, longitude=96.48515138)
    lat_lon5.to_latlon()

    lps = LpsPoint(hemisphere="S", easting=197000, northing=197000)
    extreme_lat_lon = lps.to_latlon()

    lps_acc = lgrs1.to_acc()
    ltm_acc = lgrs2.to_acc()

    lps_acc.truncate(100_000).to_latlon()

    lgrs_.distance_to(lgrs1)

    lat_lon_point = LatLonPoint(90, 0)
    lat_lon_point.to_acc().validate()
