name: Lint

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Black Version
        uses: psf/black@stable
        with:
          options: "--version"
      - name: Black Check
        uses: psf/black@stable

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "src/lgrs/"
